export interface GetStateClassCHardTarget {
  path: string;
  maxCurrentHits: number;
}

export const allowedAdapterPaths = [
  'src/services/aiTools/**',
  'src/services/guidedActions/**',
  'src/components/guidedActions/**',
  'src/services/project/**',
  'src/services/projectFileService.ts',
  'src/stores/historyStore/**',
  // dockStore became a folder in packet 171; the adapter grant follows it.
  'src/stores/dockStore/**',
  'src/services/midi/**',
  'src/hooks/useMIDIRuntime.ts',
  'src/services/sam2/**',
  'src/services/matanyone/**',
  'src/services/flashboard/**',
  'src/services/mediaRuntime/**',
  'src/services/timeline/timelineRuntimeCoordinator.ts',
  'src/services/timeline/runtimeCoordinatorTypes.ts',
  'src/services/timeline/runtimeCoordinatorContracts.ts',
  'src/services/audio/AudioRecordingService.ts',
  'src/services/audio/timelineRecordingWorkflow.ts',
  'src/services/export/**',
  'src/services/render/**',
  'src/editorBoot.ts',
] as const;

export const classCHardTargets = [
  { path: 'src/components/common/MatAnyoneSetupDialog.tsx', maxCurrentHits: 4 },
  { path: 'src/components/common/Toolbar.tsx', maxCurrentHits: 2 },
  { path: 'src/components/export/exportHelpers.ts', maxCurrentHits: 2 },
  // Packets 189/208: ExportPanel is now getState-FREE (3 -> 0, entry
  // removed); hits live in the run controller + runners.
  { path: 'src/components/export/runners/ffmpegDirectExportRunner.ts', maxCurrentHits: 1 },
  { path: 'src/components/export/runners/fcpxmlExportRunner.ts', maxCurrentHits: 1 },
  { path: 'src/components/export/useExportRunController.ts', maxCurrentHits: 2 },
  { path: 'src/components/export/useExportState.ts', maxCurrentHits: 1 },
  { path: 'src/components/outputManager/OutputManager.tsx', maxCurrentHits: 1 },
  { path: 'src/components/outputManager/OutputManagerBoot.ts', maxCurrentHits: 1 },
  { path: 'src/components/outputManager/SliceInputOverlay.tsx', maxCurrentHits: 1 },
  { path: 'src/components/outputManager/SliceOutputOverlay.tsx', maxCurrentHits: 1 },
  { path: 'src/components/outputManager/TargetList.tsx', maxCurrentHits: 2 },
  { path: 'src/components/outputManager/TargetPreview.tsx', maxCurrentHits: 5 },
  { path: 'src/components/panels/audio-mixer/AudioMixerPanel.tsx', maxCurrentHits: 30 },
  { path: 'src/components/panels/color/ColorEditor.tsx', maxCurrentHits: 1 },
  { path: 'src/components/panels/HistoryPanel.tsx', maxCurrentHits: 1 },
  // Redistributed by packet 172: two hits moved into the extracted
  // source-monitor badge hook; MediaPanel-cluster total unchanged (7).
  // Packet 190 moved one hit into the board node-move gesture hook.
  { path: 'src/components/panels/MediaPanel.tsx', maxCurrentHits: 4 },
  { path: 'src/components/panels/media/board/useMediaBoardNodeMoveGesture.ts', maxCurrentHits: 1 },
  { path: 'src/components/panels/media/panel/useMediaPanelSourceMonitorBadges.ts', maxCurrentHits: 2 },
  { path: 'src/components/panels/nodes/NodeWorkspacePanel.tsx', maxCurrentHits: 1 },
  { path: 'src/components/panels/properties/AnalysisTab.tsx', maxCurrentHits: 1 },
  { path: 'src/components/panels/properties/AudioBusPropertiesTabs.tsx', maxCurrentHits: 10 },
  { path: 'src/components/panels/properties/BlendshapesTab.tsx', maxCurrentHits: 1 },
  { path: 'src/components/panels/properties/CameraTab.tsx', maxCurrentHits: 3 },
  { path: 'src/components/panels/properties/EffectsTab.tsx', maxCurrentHits: 1 },
  { path: 'src/components/panels/properties/GaussianSplatTab.tsx', maxCurrentHits: 3 },
  { path: 'src/components/panels/properties/index.tsx', maxCurrentHits: 3 },
  { path: 'src/components/panels/properties/LottieTab.tsx', maxCurrentHits: 2 },
  { path: 'src/components/panels/properties/MasksTab.tsx', maxCurrentHits: 6 },
  { path: 'src/components/panels/properties/shared.tsx', maxCurrentHits: 7 },
  { path: 'src/components/panels/properties/SplatEffectorTab.tsx', maxCurrentHits: 3 },
  { path: 'src/components/panels/properties/ThreeDTextTab.tsx', maxCurrentHits: 1 },
  { path: 'src/components/panels/properties/TranscriptTab.tsx', maxCurrentHits: 3 },
  { path: 'src/components/panels/properties/TransformTab.tsx', maxCurrentHits: 2 },
  { path: 'src/components/panels/properties/VolumeTab.tsx', maxCurrentHits: 2 },
  { path: 'src/components/panels/SAM2Panel.tsx', maxCurrentHits: 32 },
  { path: 'src/components/panels/TextTab.tsx', maxCurrentHits: 2 },
  { path: 'src/components/pianoRoll/PianoRoll.tsx', maxCurrentHits: 4 },
  { path: 'src/components/pianoRoll/PianoRollBoot.ts', maxCurrentHits: 1 },
  { path: 'src/components/preview/MaskOverlay.tsx', maxCurrentHits: 2 },
  { path: 'src/components/preview/MultiPreviewSlot.tsx', maxCurrentHits: 4 },
  // Ratchet trail: 27 -> 23 (packet 188, adapter layer), -> 20+3 (191,
  // source config), -> 17+3+2 (209, wheel handler). Cluster total 22 (one
  // hit retired entirely in 209).
  { path: 'src/components/preview/Preview.tsx', maxCurrentHits: 17 },
  { path: 'src/components/preview/usePreviewSourceConfig.ts', maxCurrentHits: 3 },
  { path: 'src/components/preview/usePreviewWheelHandler.ts', maxCurrentHits: 2 },
  { path: 'src/components/preview/SAM2Overlay.tsx', maxCurrentHits: 2 },
  { path: 'src/components/preview/SceneObjectOverlay.tsx', maxCurrentHits: 3 },
  { path: 'src/components/preview/sceneObjectOverlayMath.ts', maxCurrentHits: 1 },
  { path: 'src/components/preview/SourceMonitor.tsx', maxCurrentHits: 1 },
  { path: 'src/components/preview/useMaskDrag.ts', maxCurrentHits: 2 },
  { path: 'src/components/preview/useMaskEdgeDrag.ts', maxCurrentHits: 3 },
  { path: 'src/components/preview/useMaskVertexDrag.ts', maxCurrentHits: 6 },
  { path: 'src/components/timeline/components/SlotGridTimeOverlay.tsx', maxCurrentHits: 3 },
  { path: 'src/components/timeline/components/TimelineHeaderAudioControls.tsx', maxCurrentHits: 12 },
  { path: 'src/components/timeline/components/TimelineHeaderAudioSends.tsx', maxCurrentHits: 6 },
  { path: 'src/components/timeline/components/TimelineHeaderPropertyLabels.tsx', maxCurrentHits: 1 },
  { path: 'src/components/timeline/components/TimelineHeaderPropertyRow.tsx', maxCurrentHits: 2 },
  { path: 'src/components/timeline/components/TimelineSectionHeaders.tsx', maxCurrentHits: 5 },
  { path: 'src/components/timeline/hooks/externalDropImmediatePreview.ts', maxCurrentHits: 1 },
  { path: 'src/components/timeline/hooks/useAutoFeatures.ts', maxCurrentHits: 2 },
  { path: 'src/components/timeline/hooks/useClipDoubleClick.ts', maxCurrentHits: 1 },
  { path: 'src/components/timeline/hooks/useClipDrag.ts', maxCurrentHits: 1 },
  { path: 'src/components/timeline/hooks/useClipInteractionShellModuleCommandDispatcher.ts', maxCurrentHits: 3 },
  { path: 'src/components/timeline/hooks/useExternalDrop.ts', maxCurrentHits: 1 },
  { path: 'src/components/timeline/hooks/useLayerSync.ts', maxCurrentHits: 3 },
  { path: 'src/components/timeline/hooks/useMarqueeSelection.ts', maxCurrentHits: 2 },
  { path: 'src/components/timeline/hooks/useMidiClipDraw.ts', maxCurrentHits: 2 },
  { path: 'src/components/timeline/hooks/usePlaybackLoop.ts', maxCurrentHits: 4 },
  { path: 'src/components/timeline/hooks/useTimelineKeyboard.ts', maxCurrentHits: 9 },
  { path: 'src/components/timeline/hooks/useTimelinePlayheadDisplay.ts', maxCurrentHits: 1 },
  { path: 'src/components/timeline/hooks/useTimelineSourceMonitorDismiss.ts', maxCurrentHits: 1 },
  { path: 'src/components/timeline/hooks/useTimelineSplitDividerDrag.ts', maxCurrentHits: 2 },
  { path: 'src/components/timeline/hooks/useTimelineStableActionBindings.ts', maxCurrentHits: 1 },
  { path: 'src/components/timeline/hooks/useTimelineTrackHeightWheel.ts', maxCurrentHits: 1 },
  { path: 'src/components/timeline/hooks/useTimelineTrackPointerTools.ts', maxCurrentHits: 5 },
  { path: 'src/components/timeline/hooks/useTimelineTrackResize.ts', maxCurrentHits: 2 },
  { path: 'src/components/timeline/SlotGrid.tsx', maxCurrentHits: 14 },
  { path: 'src/components/timeline/slotGridAnimation.ts', maxCurrentHits: 3 },
  { path: 'src/components/timeline/TimelineContextMenu.tsx', maxCurrentHits: 5 },
  { path: 'src/components/timeline/TimelineControls.tsx', maxCurrentHits: 12 },
  { path: 'src/components/timeline/TimelineHeader.tsx', maxCurrentHits: 1 },
  { path: 'src/components/timeline/tools/timelineToolCommands.ts', maxCurrentHits: 1 },
  { path: 'src/components/timeline/TrackContextMenu.tsx', maxCurrentHits: 5 },
  { path: 'src/components/timeline/utils/layerSyncProxyFrames.ts', maxCurrentHits: 2 },
  { path: 'src/engine/audio/AudioExportPipeline.ts', maxCurrentHits: 3 },
  { path: 'src/engine/export/ClipPreparation.ts', maxCurrentHits: 2 },
  { path: 'src/engine/export/ExportLayerBuilder.ts', maxCurrentHits: 7 },
  { path: 'src/engine/export/ExportMaskTextures.ts', maxCurrentHits: 1 },
  { path: 'src/engine/export/FrameExporter.ts', maxCurrentHits: 4 },
  { path: 'src/engine/export/preloadGaussianSplats.ts', maxCurrentHits: 4 },
  { path: 'src/engine/managers/OutputWindowManager.ts', maxCurrentHits: 6 },
  { path: 'src/engine/render/LayerCollector.ts', maxCurrentHits: 7 },
  { path: 'src/engine/render/NestedCompRenderer.ts', maxCurrentHits: 10 },
  { path: 'src/engine/render/RenderDispatcher.ts', maxCurrentHits: 16 },
  { path: 'src/engine/scene/SceneCameraUtils.ts', maxCurrentHits: 7 },
  { path: 'src/engine/scene/SceneEffectorUtils.ts', maxCurrentHits: 2 },
  { path: 'src/engine/WebGPUEngine.ts', maxCurrentHits: 12 },
  { path: 'src/hooks/useEngine.ts', maxCurrentHits: 25 },
  { path: 'src/hooks/useGlobalHistory.ts', maxCurrentHits: 3 },
  { path: 'src/services/audio/audioDiagnostics.ts', maxCurrentHits: 1 },
  { path: 'src/services/audio/ClipAudioAnalysisOrchestrator.ts', maxCurrentHits: 1 },
  { path: 'src/services/audio/ClipAudioRenderService.ts', maxCurrentHits: 1 },
  { path: 'src/services/audio/midiPlaybackScheduler.ts', maxCurrentHits: 6 },
  { path: 'src/services/audio/stemSeparation/StemSeparationService.ts', maxCurrentHits: 1 },
  { path: 'src/services/audioAnalyzer.ts', maxCurrentHits: 1 },
  { path: 'src/services/clipAnalyzer.ts', maxCurrentHits: 4 },
  { path: 'src/services/clipTranscriber.ts', maxCurrentHits: 4 },
  { path: 'src/services/cloudAiService.ts', maxCurrentHits: 2 },
  { path: 'src/services/compositionAudioMixer.ts', maxCurrentHits: 2 },
  { path: 'src/services/compositionRenderer.ts', maxCurrentHits: 12 },
  { path: 'src/services/layerBuilder/AudioSyncHandler.ts', maxCurrentHits: 2 },
  { path: 'src/services/layerBuilder/audioTrackRuntimeElements.ts', maxCurrentHits: 1 },
  { path: 'src/services/layerBuilder/audioTrackStemBufferMixerSessions.ts', maxCurrentHits: 1 },
  { path: 'src/services/layerBuilder/audioTrackStemPreviewElements.ts', maxCurrentHits: 1 },
  { path: 'src/services/layerBuilder/AudioTrackSyncManager.ts', maxCurrentHits: 7 },
  { path: 'src/services/layerBuilder/FrameContext.ts', maxCurrentHits: 2 },
  { path: 'src/services/layerBuilder/layerBuilder3dLayers.ts', maxCurrentHits: 1 },
  { path: 'src/services/layerBuilder/layerBuilder3dSources.ts', maxCurrentHits: 3 },
  { path: 'src/services/layerBuilder/layerBuilderMotionLayers.ts', maxCurrentHits: 1 },
  { path: 'src/services/layerBuilder/layerBuilderNestedLayers.ts', maxCurrentHits: 1 },
  { path: 'src/services/layerBuilder/LayerBuilderService.ts', maxCurrentHits: 5 },
  { path: 'src/services/layerBuilder/videoSyncHtmlSeekCoordinator.ts', maxCurrentHits: 2 },
  { path: 'src/services/layerPlaybackManager.ts', maxCurrentHits: 6 },
  { path: 'src/services/multicamAnalyzer.ts', maxCurrentHits: 1 },
  { path: 'src/services/performanceMonitor.ts', maxCurrentHits: 1 },
  { path: 'src/services/playbackHealthMonitor.ts', maxCurrentHits: 7 },
  { path: 'src/services/properties/registerCoreProperties.ts', maxCurrentHits: 1 },
  { path: 'src/services/proxyFrameCache.ts', maxCurrentHits: 4 },
  { path: 'src/services/renderScheduler.ts', maxCurrentHits: 12 },
  { path: 'src/services/sceneDescriber.ts', maxCurrentHits: 5 },
  { path: 'src/services/shortcutRegistry.ts', maxCurrentHits: 1 },
  { path: 'src/services/slotDeckManager.ts', maxCurrentHits: 6 },
  { path: 'src/services/thumbnailRenderer.ts', maxCurrentHits: 1 },
  { path: 'src/services/timeline/renderTargetRuntimeReporting.ts', maxCurrentHits: 3 },
  { path: 'src/services/timeline/timelineAudioArtifactGenerationWarmup.ts', maxCurrentHits: 3 },
  { path: 'src/services/timeline/timelineExternalDropCommandExecutor.ts', maxCurrentHits: 2 },
  { path: 'src/services/timeline/timelineExternalDropMediaResolver.ts', maxCurrentHits: 2 },
  { path: 'src/services/timeline/timelineSourceWaveformWarmup.ts', maxCurrentHits: 2 },
  { path: 'src/services/timeline/timelineThumbnailGenerationWarmup.ts', maxCurrentHits: 4 },
  { path: 'src/services/timelinePlacementCommands.ts', maxCurrentHits: 13 },
  { path: 'src/services/timelineSubcomposition.ts', maxCurrentHits: 9 },
  { path: 'src/services/whisperService.ts', maxCurrentHits: 1 },
  { path: 'src/stores/flashboardStore/activeGenerationRecords.ts', maxCurrentHits: 2 },
  { path: 'src/stores/mediaDownloadStore.ts', maxCurrentHits: 6 },
  { path: 'src/stores/mediaStore/helpers/gaussianSplatSequenceImport.ts', maxCurrentHits: 1 },
  { path: 'src/stores/mediaStore/helpers/importPipeline.ts', maxCurrentHits: 1 },
  { path: 'src/stores/mediaStore/helpers/modelSequenceImport.ts', maxCurrentHits: 1 },
  { path: 'src/stores/mediaStore/init.ts', maxCurrentHits: 6 },
  // Redistributed by packet 186: the compositionSlice split moved its 10
  // hits into six role modules; cluster total unchanged (10).
  { path: 'src/stores/mediaStore/slices/composition/activeTimelineSync.ts', maxCurrentHits: 2 },
  { path: 'src/stores/mediaStore/slices/composition/crudActions.ts', maxCurrentHits: 1 },
  { path: 'src/stores/mediaStore/slices/composition/resizeTransforms.ts', maxCurrentHits: 1 },
  { path: 'src/stores/mediaStore/slices/composition/slotAssignmentActions.ts', maxCurrentHits: 3 },
  { path: 'src/stores/mediaStore/slices/composition/tabActions.ts', maxCurrentHits: 1 },
  { path: 'src/stores/mediaStore/slices/composition/timelineSwitchBridge.ts', maxCurrentHits: 2 },
  // Redistributed by packet 183: the fileManageSlice split moved its 8 hits
  // into five role modules; cluster total unchanged (8).
  { path: 'src/stores/mediaStore/slices/fileManage/deleteActions.ts', maxCurrentHits: 1 },
  { path: 'src/stores/mediaStore/slices/fileManage/deleteRuntimeCleanup.ts', maxCurrentHits: 3 },
  { path: 'src/stores/mediaStore/slices/fileManage/mediaUsagePlanner.ts', maxCurrentHits: 1 },
  { path: 'src/stores/mediaStore/slices/fileManage/sourceReplacementCache.ts', maxCurrentHits: 1 },
  { path: 'src/stores/mediaStore/slices/fileManage/timelineClipReload.ts', maxCurrentHits: 2 },
  { path: 'src/stores/mediaStore/slices/projectSlice.ts', maxCurrentHits: 1 },
  { path: 'src/stores/mediaStore/slices/proxySlice.ts', maxCurrentHits: 3 },
  { path: 'src/stores/multicamStore.ts', maxCurrentHits: 2 },
  { path: 'src/stores/renderTargetStore.ts', maxCurrentHits: 5 },
  { path: 'src/stores/sliceStore.ts', maxCurrentHits: 5 },
  { path: 'src/stores/timeline/audioEdit/audioBakeActions.ts', maxCurrentHits: 2 },
  { path: 'src/stores/timeline/cameraClipSlice.ts', maxCurrentHits: 1 },
  { path: 'src/stores/timeline/clip/addAudioClip.ts', maxCurrentHits: 2 },
  { path: 'src/stores/timeline/clip/addClipMediaSource.ts', maxCurrentHits: 1 },
  { path: 'src/stores/timeline/clip/addImageClip.ts', maxCurrentHits: 1 },
  { path: 'src/stores/timeline/clip/addVideoClip.ts', maxCurrentHits: 3 },
  { path: 'src/stores/timeline/clip/clipAudioAnalysisShared.ts', maxCurrentHits: 1 },
  { path: 'src/stores/timeline/clip/completeDownload.ts', maxCurrentHits: 1 },
  { path: 'src/stores/timeline/clip/compositionClipActions.ts', maxCurrentHits: 1 },
  { path: 'src/stores/timeline/clip/upgradeToNativeDecoder.ts', maxCurrentHits: 6 },
  { path: 'src/stores/timeline/clip/videoLinkedAudioLoader.ts', maxCurrentHits: 1 },
  { path: 'src/stores/timeline/clip/videoThumbnailLoader.ts', maxCurrentHits: 1 },
  { path: 'src/stores/timeline/clipboardSlice.ts', maxCurrentHits: 1 },
  { path: 'src/stores/timeline/constants.ts', maxCurrentHits: 2 },
  { path: 'src/stores/timeline/keyframes/vectorAnimationKeyframeValues.ts', maxCurrentHits: 3 },
  { path: 'src/stores/timeline/mathSceneClipSlice.ts', maxCurrentHits: 1 },
  { path: 'src/stores/timeline/meshClipSlice.ts', maxCurrentHits: 1 },
  { path: 'src/stores/timeline/playbackSlice.ts', maxCurrentHits: 2 },
  { path: 'src/stores/timeline/proxyCacheSlice.ts', maxCurrentHits: 1 },
  { path: 'src/stores/timeline/ramPreviewSlice.ts', maxCurrentHits: 1 },
  { path: 'src/stores/timeline/serialization/serializableTimelineState.ts', maxCurrentHits: 1 },
  { path: 'src/stores/timeline/serializationUtils.ts', maxCurrentHits: 2 },
  { path: 'src/stores/timeline/solidClipSlice.ts', maxCurrentHits: 2 },
  { path: 'src/stores/timeline/splatEffectorClipSlice.ts', maxCurrentHits: 1 },
  { path: 'src/stores/timeline/stemSeparationSlice.ts', maxCurrentHits: 3 },
  { path: 'src/stores/timeline/textClipSlice.ts', maxCurrentHits: 2 },
  { path: 'src/stores/timeline/tracks/trackAudioState.ts', maxCurrentHits: 1 },
  { path: 'src/stores/timeline/trackSlice.ts', maxCurrentHits: 1 },
  { path: 'src/stores/timeline/videoBakeSlice.ts', maxCurrentHits: 1 },
] as const satisfies readonly GetStateClassCHardTarget[];

export const getStateAccessPolicyBaselines = {
  allowedAdapterPathCount: 21,
  // Running redistribution log: 178 (packet 172), 182 (183), 187 (186),
  // 189 (189+190: ExportPanel/MediaPanel hits moved into runner/board-hook
  // entries). Totals conserved per redistribution; max-hits ratchets DOWN
  // only (669 -> 665 via the packet-188 Preview ceiling cut).
  classCHardTargetFileCount: 192,
  // 669 -> 665 (packet 188 Preview cut) -> 664 (packet 209 retired one hit).
  classCHardTargetMaxHits: 664,
} as const;
