export interface GetStateClassCHardTarget {
  path: string;
  maxCurrentHits: number;
}

export const allowedAdapterPaths = [
  'src/services/aiTools/**',
  'src/services/guidedActions/**',
  'src/components/guidedActions/**',
  'src/services/project/**',
  'src/services/projectFileService.ts',
  'src/stores/historyStore/**',
  // dockStore became a folder in packet 171; the adapter grant follows it.
  'src/stores/dockStore/**',
  'src/services/midi/**',
  'src/hooks/useMIDIRuntime.ts',
  'src/services/sam2/**',
  'src/services/matanyone/**',
  'src/services/flashboard/**',
  'src/services/mediaRuntime/**',
  'src/services/timeline/timelineRuntimeCoordinator.ts',
  'src/services/timeline/runtimeCoordinatorTypes.ts',
  'src/services/timeline/runtimeCoordinatorContracts.ts',
  'src/services/audio/AudioRecordingService.ts',
  // Packet 221: commit-to-timeline adapter grant follows the split module.
  'src/services/audio/recording/commitRecording.ts',
  'src/services/audio/timelineRecordingWorkflow.ts',
  'src/services/export/**',
  'src/services/render/**',
  'src/editorBoot.ts',
] as const;

export const classCHardTargets = [
  { path: 'src/components/common/MatAnyoneSetupDialog.tsx', maxCurrentHits: 4 },
  { path: 'src/components/common/Toolbar.tsx', maxCurrentHits: 2 },
  { path: 'src/components/export/exportHelpers.ts', maxCurrentHits: 2 },
  // 189/208: ExportPanel getState-FREE; hits live in run controller/runners.
  { path: 'src/components/export/runners/ffmpegDirectExportRunner.ts', maxCurrentHits: 1 },
  { path: 'src/components/export/runners/fcpxmlExportRunner.ts', maxCurrentHits: 1 },
  { path: 'src/components/export/useExportRunController.ts', maxCurrentHits: 2 },
  { path: 'src/components/export/useExportState.ts', maxCurrentHits: 1 },
  { path: 'src/components/outputManager/OutputManager.tsx', maxCurrentHits: 1 },
  { path: 'src/components/outputManager/OutputManagerBoot.ts', maxCurrentHits: 1 },
  { path: 'src/components/outputManager/SliceInputOverlay.tsx', maxCurrentHits: 1 },
  { path: 'src/components/outputManager/SliceOutputOverlay.tsx', maxCurrentHits: 1 },
  { path: 'src/components/outputManager/TargetList.tsx', maxCurrentHits: 2 },
  { path: 'src/components/outputManager/TargetPreview.tsx', maxCurrentHits: 5 },
  // Packet 279: 30 -> 6+10+3+10+1 (mixer strip/fx modules), total conserved.
  { path: 'src/components/panels/audio-mixer/AudioMixerPanel.tsx', maxCurrentHits: 6 },
  { path: 'src/components/panels/audio-mixer/TrackMixerStrip.tsx', maxCurrentHits: 10 },
  { path: 'src/components/panels/audio-mixer/MasterMixerStrip.tsx', maxCurrentHits: 3 },
  { path: 'src/components/panels/audio-mixer/MixerFxWindow.tsx', maxCurrentHits: 10 },
  { path: 'src/components/panels/audio-mixer/MixerTrackColorMenu.tsx', maxCurrentHits: 1 },
  { path: 'src/components/panels/color/ColorEditor.tsx', maxCurrentHits: 1 },
  { path: 'src/components/panels/HistoryPanel.tsx', maxCurrentHits: 1 },
  // MediaPanel trail: badge hook (172), node-move hook (190),
  // composition-settings hook (218). Cluster total 7.
  { path: 'src/components/panels/MediaPanel.tsx', maxCurrentHits: 3 },
  { path: 'src/components/panels/media/board/useMediaBoardNodeMoveGesture.ts', maxCurrentHits: 1 },
  { path: 'src/components/panels/media/panel/useMediaPanelCompositionSettings.ts', maxCurrentHits: 1 },
  { path: 'src/components/panels/media/panel/useMediaPanelSourceMonitorBadges.ts', maxCurrentHits: 2 },
  { path: 'src/components/panels/nodes/NodeWorkspacePanel.tsx', maxCurrentHits: 1 },
  { path: 'src/components/panels/properties/AnalysisTab.tsx', maxCurrentHits: 1 },
  { path: 'src/components/panels/properties/AudioBusPropertiesTabs.tsx', maxCurrentHits: 10 },
  { path: 'src/components/panels/properties/BlendshapesTab.tsx', maxCurrentHits: 1 },
  { path: 'src/components/panels/properties/CameraTab.tsx', maxCurrentHits: 3 },
  { path: 'src/components/panels/properties/EffectsTab.tsx', maxCurrentHits: 1 },
  { path: 'src/components/panels/properties/GaussianSplatTab.tsx', maxCurrentHits: 3 },
  { path: 'src/components/panels/properties/index.tsx', maxCurrentHits: 3 },
  { path: 'src/components/panels/properties/LottieTab.tsx', maxCurrentHits: 2 },
  // Packet 287: 6 -> 1+1+1+1+2 (masksTab modules), total conserved.
  { path: 'src/components/panels/properties/MasksTab.tsx', maxCurrentHits: 1 },
  { path: 'src/components/panels/properties/masksTab/MaskItem.tsx', maxCurrentHits: 1 },
  { path: 'src/components/panels/properties/masksTab/MaskPathKeyframeToggle.tsx', maxCurrentHits: 1 },
  { path: 'src/components/panels/properties/masksTab/useMaskKeybindings.ts', maxCurrentHits: 1 },
  { path: 'src/components/panels/properties/masksTab/useMaskPanelBatch.ts', maxCurrentHits: 2 },
  { path: 'src/components/panels/properties/shared.tsx', maxCurrentHits: 7 },
  { path: 'src/components/panels/properties/SplatEffectorTab.tsx', maxCurrentHits: 3 },
  { path: 'src/components/panels/properties/ThreeDTextTab.tsx', maxCurrentHits: 1 },
  { path: 'src/components/panels/properties/TranscriptTab.tsx', maxCurrentHits: 3 },
  { path: 'src/components/panels/properties/TransformTab.tsx', maxCurrentHits: 2 },
  { path: 'src/components/panels/properties/VolumeTab.tsx', maxCurrentHits: 2 },
  // Packet 259: 32 -> 28 + 4 (MatAnyone file helpers), total conserved.
  { path: 'src/components/panels/SAM2Panel.tsx', maxCurrentHits: 28 },
  { path: 'src/components/panels/sam2/MatAnyoneFileHelpers.ts', maxCurrentHits: 4 },
  { path: 'src/components/panels/TextTab.tsx', maxCurrentHits: 2 },
  { path: 'src/components/pianoRoll/PianoRoll.tsx', maxCurrentHits: 4 },
  { path: 'src/components/pianoRoll/PianoRollBoot.ts', maxCurrentHits: 1 },
  { path: 'src/components/preview/MaskOverlay.tsx', maxCurrentHits: 2 },
  { path: 'src/components/preview/MultiPreviewSlot.tsx', maxCurrentHits: 4 },
  // Preview trail: 27 ->23(188) ->20+3(191) ->17+3+2(209, one retired)
  // ->1+16 camera hooks (227). Cluster total 22.
  { path: 'src/components/preview/Preview.tsx', maxCurrentHits: 1 },
  { path: 'src/components/preview/usePreviewEditCameraController.ts', maxCurrentHits: 8 },
  { path: 'src/components/preview/usePreviewSceneCameraActions.ts', maxCurrentHits: 7 },
  { path: 'src/components/preview/usePreviewEditCameraConfig.ts', maxCurrentHits: 1 },
  { path: 'src/components/preview/usePreviewSourceConfig.ts', maxCurrentHits: 3 },
  { path: 'src/components/preview/usePreviewWheelHandler.ts', maxCurrentHits: 2 },
  { path: 'src/components/preview/SAM2Overlay.tsx', maxCurrentHits: 2 },
  { path: 'src/components/preview/SceneObjectOverlay.tsx', maxCurrentHits: 3 },
  { path: 'src/components/preview/sceneObjectOverlayMath.ts', maxCurrentHits: 1 },
  { path: 'src/components/preview/SourceMonitor.tsx', maxCurrentHits: 1 },
  { path: 'src/components/preview/useMaskDrag.ts', maxCurrentHits: 2 },
  { path: 'src/components/preview/useMaskEdgeDrag.ts', maxCurrentHits: 3 },
  { path: 'src/components/preview/useMaskVertexDrag.ts', maxCurrentHits: 6 },
  { path: 'src/components/timeline/components/SlotGridTimeOverlay.tsx', maxCurrentHits: 3 },
  { path: 'src/components/timeline/components/TimelineHeaderAudioControls.tsx', maxCurrentHits: 12 },
  { path: 'src/components/timeline/components/TimelineHeaderAudioSends.tsx', maxCurrentHits: 6 },
  { path: 'src/components/timeline/components/TimelineHeaderPropertyLabels.tsx', maxCurrentHits: 1 },
  { path: 'src/components/timeline/components/TimelineHeaderPropertyRow.tsx', maxCurrentHits: 2 },
  { path: 'src/components/timeline/components/TimelineSectionHeaders.tsx', maxCurrentHits: 5 },
  { path: 'src/components/timeline/hooks/externalDropImmediatePreview.ts', maxCurrentHits: 1 },
  { path: 'src/components/timeline/hooks/useAutoFeatures.ts', maxCurrentHits: 2 },
  { path: 'src/components/timeline/hooks/useClipDoubleClick.ts', maxCurrentHits: 1 },
  { path: 'src/components/timeline/hooks/useClipDrag.ts', maxCurrentHits: 1 },
  { path: 'src/components/timeline/hooks/useClipInteractionShellModuleCommandDispatcher.ts', maxCurrentHits: 3 },
  { path: 'src/components/timeline/hooks/useExternalDrop.ts', maxCurrentHits: 1 },
  { path: 'src/components/timeline/hooks/useLayerSync.ts', maxCurrentHits: 3 },
  { path: 'src/components/timeline/hooks/useMarqueeSelection.ts', maxCurrentHits: 2 },
  { path: 'src/components/timeline/hooks/useMidiClipDraw.ts', maxCurrentHits: 2 },
  { path: 'src/components/timeline/hooks/usePlaybackLoop.ts', maxCurrentHits: 4 },
  { path: 'src/components/timeline/hooks/useTimelineKeyboard.ts', maxCurrentHits: 9 },
  { path: 'src/components/timeline/hooks/useTimelinePlayheadDisplay.ts', maxCurrentHits: 1 },
  { path: 'src/components/timeline/hooks/useTimelineSourceMonitorDismiss.ts', maxCurrentHits: 1 },
  { path: 'src/components/timeline/hooks/useTimelineSplitDividerDrag.ts', maxCurrentHits: 2 },
  { path: 'src/components/timeline/hooks/useTimelineStableActionBindings.ts', maxCurrentHits: 1 },
  { path: 'src/components/timeline/hooks/useTimelineTrackHeightWheel.ts', maxCurrentHits: 1 },
  { path: 'src/components/timeline/hooks/useTimelineTrackPointerTools.ts', maxCurrentHits: 5 },
  { path: 'src/components/timeline/hooks/useTimelineTrackResize.ts', maxCurrentHits: 2 },
  { path: 'src/components/timeline/SlotGrid.tsx', maxCurrentHits: 14 },
  { path: 'src/components/timeline/slotGridAnimation.ts', maxCurrentHits: 3 },
  { path: 'src/components/timeline/TimelineContextMenu.tsx', maxCurrentHits: 5 },
  { path: 'src/components/timeline/TimelineControls.tsx', maxCurrentHits: 12 },
  { path: 'src/components/timeline/TimelineHeader.tsx', maxCurrentHits: 1 },
  { path: 'src/components/timeline/tools/timelineToolCommands.ts', maxCurrentHits: 1 },
  { path: 'src/components/timeline/TrackContextMenu.tsx', maxCurrentHits: 5 },
  { path: 'src/components/timeline/utils/layerSyncProxyFrames.ts', maxCurrentHits: 2 },
  { path: 'src/engine/audio/AudioExportPipeline.ts', maxCurrentHits: 3 },
  { path: 'src/engine/export/ClipPreparation.ts', maxCurrentHits: 2 },
  // Packet 291: 7 -> 0 entry + 1+4+1 modules (one site retired via shared
  // lookup; maxHits ratchets 658 -> 657).
  { path: 'src/engine/export/layerBuilder/baseLayers.ts', maxCurrentHits: 1 },
  { path: 'src/engine/export/layerBuilder/sourceLookup.ts', maxCurrentHits: 4 },
  { path: 'src/engine/export/layerBuilder/textLayers.ts', maxCurrentHits: 1 },
  { path: 'src/engine/export/ExportMaskTextures.ts', maxCurrentHits: 1 },
  // Packet 307: 4 -> 3 + 1 (preview publisher), total conserved.
  { path: 'src/engine/export/FrameExporter.ts', maxCurrentHits: 3 },
  { path: 'src/engine/export/frameExporter/ExportPreviewPublisher.ts', maxCurrentHits: 1 },
  { path: 'src/engine/export/preloadGaussianSplats.ts', maxCurrentHits: 4 },
  { path: 'src/engine/managers/OutputWindowManager.ts', maxCurrentHits: 6 },
  // Packet 239: LayerCollector 7 -> collector branch modules, conserved.
  { path: 'src/engine/render/layerCollector/htmlVideoCollector.ts', maxCurrentHits: 1 },
  { path: 'src/engine/render/layerCollector/htmlVideoFrameCache.ts', maxCurrentHits: 1 },
  { path: 'src/engine/render/layerCollector/htmlVideoNotReadyCollector.ts', maxCurrentHits: 1 },
  { path: 'src/engine/render/layerCollector/htmlVideoReadyCollector.ts', maxCurrentHits: 1 },
  { path: 'src/engine/render/layerCollector/webCodecsCollector.ts', maxCurrentHits: 3 },
  // Packet 246: 10 -> 1 + 8 + 1 (nestedComp modules), total conserved.
  { path: 'src/engine/render/NestedCompRenderer.ts', maxCurrentHits: 1 },
  { path: 'src/engine/render/nestedComp/htmlVideoPreview.ts', maxCurrentHits: 8 },
  { path: 'src/engine/render/nestedComp/sharedScene.ts', maxCurrentHits: 1 },
  // Packet 231 moved 5 hits into the scene-3D/target-preview facets and the
  // old 16-ceiling slack (actual was 11) is retired: 16 -> 6 + 2 + 2 + 1.
  { path: 'src/engine/render/RenderDispatcher.ts', maxCurrentHits: 6 },
  { path: 'src/engine/render/dispatcher/sharedScene3DProcessor.ts', maxCurrentHits: 2 },
  { path: 'src/engine/render/dispatcher/targetPreviewLayerCollector.ts', maxCurrentHits: 2 },
  { path: 'src/engine/render/dispatcher/targetPreviewRenderer.ts', maxCurrentHits: 1 },
  { path: 'src/engine/scene/SceneCameraUtils.ts', maxCurrentHits: 7 },
  { path: 'src/engine/scene/SceneEffectorUtils.ts', maxCurrentHits: 2 },
  // Packet 254: 12 -> 5 + 7 (output-window controller), total conserved.
  { path: 'src/engine/WebGPUEngine.ts', maxCurrentHits: 5 },
  { path: 'src/engine/engineCore/outputWindowController.ts', maxCurrentHits: 7 },
  // Packet 306: 25 -> 12+4+3+3+2 (engine sync hooks; maxHits 657 -> 656).
  { path: 'src/hooks/useEngine.ts', maxCurrentHits: 12 },
  { path: 'src/hooks/engine/useEngineMaskTextureSync.ts', maxCurrentHits: 4 },
  { path: 'src/hooks/engine/useEngineRenderWakeSubscriptions.ts', maxCurrentHits: 3 },
  { path: 'src/hooks/engine/useEngineResolutionSync.ts', maxCurrentHits: 3 },
  { path: 'src/hooks/engine/useEngineTimelineStateSync.ts', maxCurrentHits: 2 },
  { path: 'src/hooks/useGlobalHistory.ts', maxCurrentHits: 3 },
  { path: 'src/services/audio/audioDiagnostics.ts', maxCurrentHits: 1 },
  { path: 'src/services/audio/ClipAudioAnalysisOrchestrator.ts', maxCurrentHits: 1 },
  // Packet 220 split: ClipAudioRenderService is getState-free; its single
  // hit moved into the spectral mask provider (cluster total conserved).
  { path: 'src/services/audio/clipRender/spectralImageMaskProvider.ts', maxCurrentHits: 1 },
  { path: 'src/services/audio/midiPlaybackScheduler.ts', maxCurrentHits: 6 },
  { path: 'src/services/audio/stemSeparation/StemSeparationService.ts', maxCurrentHits: 1 },
  { path: 'src/services/audioAnalyzer.ts', maxCurrentHits: 1 },
  { path: 'src/services/clipAnalyzer.ts', maxCurrentHits: 4 },
  // Packet 267: 4 -> 2 + 2 (transcription artifact module), total conserved.
  { path: 'src/services/clipTranscriber.ts', maxCurrentHits: 2 },
  { path: 'src/services/transcription/artifactPersistence.ts', maxCurrentHits: 2 },
  { path: 'src/services/cloudAiService.ts', maxCurrentHits: 2 },
  { path: 'src/services/compositionAudioMixer.ts', maxCurrentHits: 2 },
  // 12 -> 11: packet 237 retired one hit during the composition render split.
  { path: 'src/services/compositionRenderer.ts', maxCurrentHits: 11 },
  { path: 'src/services/layerBuilder/AudioSyncHandler.ts', maxCurrentHits: 2 },
  { path: 'src/services/layerBuilder/audioTrackRuntimeElements.ts', maxCurrentHits: 1 },
  { path: 'src/services/layerBuilder/audioTrackStemBufferMixerSessions.ts', maxCurrentHits: 1 },
  { path: 'src/services/layerBuilder/audioTrackStemPreviewElements.ts', maxCurrentHits: 1 },
  { path: 'src/services/layerBuilder/AudioTrackSyncManager.ts', maxCurrentHits: 7 },
  { path: 'src/services/layerBuilder/FrameContext.ts', maxCurrentHits: 2 },
  { path: 'src/services/layerBuilder/layerBuilder3dLayers.ts', maxCurrentHits: 1 },
  { path: 'src/services/layerBuilder/layerBuilder3dSources.ts', maxCurrentHits: 3 },
  { path: 'src/services/layerBuilder/layerBuilderMotionLayers.ts', maxCurrentHits: 1 },
  { path: 'src/services/layerBuilder/layerBuilderNestedLayers.ts', maxCurrentHits: 1 },
  { path: 'src/services/layerBuilder/LayerBuilderService.ts', maxCurrentHits: 5 },
  { path: 'src/services/layerBuilder/videoSyncHtmlSeekCoordinator.ts', maxCurrentHits: 2 },
  { path: 'src/services/layerPlaybackManager.ts', maxCurrentHits: 6 },
  { path: 'src/services/multicamAnalyzer.ts', maxCurrentHits: 1 },
  { path: 'src/services/performanceMonitor.ts', maxCurrentHits: 1 },
  { path: 'src/services/playbackHealthMonitor.ts', maxCurrentHits: 7 },
  // Packet 261: registrar hit moved into the vector-animation module.
  { path: 'src/services/properties/vectorAnimationProperties.ts', maxCurrentHits: 1 },
  { path: 'src/services/proxyFrameCache.ts', maxCurrentHits: 4 },
  { path: 'src/services/renderScheduler.ts', maxCurrentHits: 12 },
  { path: 'src/services/sceneDescriber.ts', maxCurrentHits: 5 },
  { path: 'src/services/shortcutRegistry.ts', maxCurrentHits: 1 },
  { path: 'src/services/slotDeckManager.ts', maxCurrentHits: 6 },
  // Packet 253 split: the single hit moved into the sampling module.
  { path: 'src/services/thumbnailRender/sampling.ts', maxCurrentHits: 1 },
  { path: 'src/services/timeline/renderTargetRuntimeReporting.ts', maxCurrentHits: 3 },
  { path: 'src/services/timeline/timelineAudioArtifactGenerationWarmup.ts', maxCurrentHits: 3 },
  { path: 'src/services/timeline/timelineExternalDropCommandExecutor.ts', maxCurrentHits: 2 },
  { path: 'src/services/timeline/timelineExternalDropMediaResolver.ts', maxCurrentHits: 2 },
  { path: 'src/services/timeline/timelineSourceWaveformWarmup.ts', maxCurrentHits: 2 },
  { path: 'src/services/timeline/timelineThumbnailGenerationWarmup.ts', maxCurrentHits: 4 },
  { path: 'src/services/timelinePlacementCommands.ts', maxCurrentHits: 13 },
  { path: 'src/services/timelineSubcomposition.ts', maxCurrentHits: 9 },
  { path: 'src/services/whisperService.ts', maxCurrentHits: 1 },
  { path: 'src/stores/flashboardStore/activeGenerationRecords.ts', maxCurrentHits: 2 },
  { path: 'src/stores/mediaDownloadStore.ts', maxCurrentHits: 6 },
  { path: 'src/stores/mediaStore/helpers/gaussianSplatSequenceImport.ts', maxCurrentHits: 1 },
  { path: 'src/stores/mediaStore/helpers/importPipeline.ts', maxCurrentHits: 1 },
  { path: 'src/stores/mediaStore/helpers/modelSequenceImport.ts', maxCurrentHits: 1 },
  { path: 'src/stores/mediaStore/init.ts', maxCurrentHits: 6 },
  // Packet 186: compositionSlice 10 -> six role modules, conserved.
  { path: 'src/stores/mediaStore/slices/composition/activeTimelineSync.ts', maxCurrentHits: 2 },
  { path: 'src/stores/mediaStore/slices/composition/crudActions.ts', maxCurrentHits: 1 },
  { path: 'src/stores/mediaStore/slices/composition/resizeTransforms.ts', maxCurrentHits: 1 },
  { path: 'src/stores/mediaStore/slices/composition/slotAssignmentActions.ts', maxCurrentHits: 3 },
  { path: 'src/stores/mediaStore/slices/composition/tabActions.ts', maxCurrentHits: 1 },
  { path: 'src/stores/mediaStore/slices/composition/timelineSwitchBridge.ts', maxCurrentHits: 2 },
  // Packet 183: fileManageSlice 8 -> five role modules, conserved.
  { path: 'src/stores/mediaStore/slices/fileManage/deleteActions.ts', maxCurrentHits: 1 },
  { path: 'src/stores/mediaStore/slices/fileManage/deleteRuntimeCleanup.ts', maxCurrentHits: 3 },
  { path: 'src/stores/mediaStore/slices/fileManage/mediaUsagePlanner.ts', maxCurrentHits: 1 },
  { path: 'src/stores/mediaStore/slices/fileManage/sourceReplacementCache.ts', maxCurrentHits: 1 },
  { path: 'src/stores/mediaStore/slices/fileManage/timelineClipReload.ts', maxCurrentHits: 2 },
  { path: 'src/stores/mediaStore/slices/projectSlice.ts', maxCurrentHits: 1 },
  { path: 'src/stores/mediaStore/slices/proxySlice.ts', maxCurrentHits: 3 },
  { path: 'src/stores/multicamStore.ts', maxCurrentHits: 2 },
  { path: 'src/stores/renderTargetStore.ts', maxCurrentHits: 5 },
  { path: 'src/stores/sliceStore.ts', maxCurrentHits: 5 },
  { path: 'src/stores/timeline/audioEdit/audioBakeActions.ts', maxCurrentHits: 2 },
  { path: 'src/stores/timeline/cameraClipSlice.ts', maxCurrentHits: 1 },
  { path: 'src/stores/timeline/clip/addAudioClip.ts', maxCurrentHits: 2 },
  { path: 'src/stores/timeline/clip/addClipMediaSource.ts', maxCurrentHits: 1 },
  { path: 'src/stores/timeline/clip/addImageClip.ts', maxCurrentHits: 1 },
  { path: 'src/stores/timeline/clip/addVideoClip.ts', maxCurrentHits: 3 },
  { path: 'src/stores/timeline/clip/clipAudioAnalysisShared.ts', maxCurrentHits: 1 },
  { path: 'src/stores/timeline/clip/completeDownload.ts', maxCurrentHits: 1 },
  { path: 'src/stores/timeline/clip/compositionClipActions.ts', maxCurrentHits: 1 },
  { path: 'src/stores/timeline/clip/upgradeToNativeDecoder.ts', maxCurrentHits: 6 },
  { path: 'src/stores/timeline/clip/videoLinkedAudioLoader.ts', maxCurrentHits: 1 },
  { path: 'src/stores/timeline/clip/videoThumbnailLoader.ts', maxCurrentHits: 1 },
  { path: 'src/stores/timeline/clipboardSlice.ts', maxCurrentHits: 1 },
  { path: 'src/stores/timeline/constants.ts', maxCurrentHits: 2 },
  { path: 'src/stores/timeline/keyframes/vectorAnimationKeyframeValues.ts', maxCurrentHits: 3 },
  { path: 'src/stores/timeline/mathSceneClipSlice.ts', maxCurrentHits: 1 },
  { path: 'src/stores/timeline/meshClipSlice.ts', maxCurrentHits: 1 },
  { path: 'src/stores/timeline/playbackSlice.ts', maxCurrentHits: 2 },
  { path: 'src/stores/timeline/proxyCacheSlice.ts', maxCurrentHits: 1 },
  { path: 'src/stores/timeline/ramPreviewSlice.ts', maxCurrentHits: 1 },
  { path: 'src/stores/timeline/serialization/serializableTimelineState.ts', maxCurrentHits: 1 },
  { path: 'src/stores/timeline/serializationUtils.ts', maxCurrentHits: 2 },
  { path: 'src/stores/timeline/solidClipSlice.ts', maxCurrentHits: 2 },
  { path: 'src/stores/timeline/splatEffectorClipSlice.ts', maxCurrentHits: 1 },
  { path: 'src/stores/timeline/stemSeparationSlice.ts', maxCurrentHits: 3 },
  { path: 'src/stores/timeline/textClipSlice.ts', maxCurrentHits: 2 },
  { path: 'src/stores/timeline/tracks/trackAudioState.ts', maxCurrentHits: 1 },
  { path: 'src/stores/timeline/trackSlice.ts', maxCurrentHits: 1 },
  { path: 'src/stores/timeline/videoBakeSlice.ts', maxCurrentHits: 1 },
] as const satisfies readonly GetStateClassCHardTarget[];

export const getStateAccessPolicyBaselines = {
  // 21 -> 22: packet-221 grant moved into recording/commitRecording.ts.
  allowedAdapterPathCount: 22,
  // Running redistribution log: 178 (packet 172), 182 (183), 187 (186),
  // 189 (189+190: ExportPanel/MediaPanel hits moved into runner/board-hook
  // entries). Totals conserved per redistribution; max-hits ratchets DOWN
  // only (669 -> 665 via the packet-188 Preview ceiling cut).
  // fileCount log (totals conserved per split redistribution):
  // 192 ->193(218) ->196(227) ->199(231) ->203(239) ->205(246) ->206(253/254)
  // ->207(259) ->208(267) ->212(279) ->216(287).
  classCHardTargetFileCount: 223,
  // 669 -> 665 (packet 188 Preview cut) -> 664 (packet 209 retired one hit)
  // -> 659 (packet 231 retired the dispatcher ceiling slack: 16 -> 11 actual)
  // -> 658 (packet 237 retired one compositionRenderer hit).
  classCHardTargetMaxHits: 656,
} as const;
